/**:
  ros__parameters:
    bev_width: 500
    bev_height: 700
    bev_origin: [250, 699]
    px_dist: 0.04
    grass_b_weight: 1.0
    grass_g_weight: 1.0
    cone_b_weight: 1.0
    cone_r_weight: 1.0
    grass_thres: 28
    cone_thres: 60
    cone_base_ratio: 0.15
    img_bot_left: [58, 702]
    img_top_left: [712, 493]
    img_top_right: [1092, 493]
    img_bot_right: [1666, 702]
    world_bot_left: [-2.6, 3.048]
    world_top_left: [-2.6, 12.192]
    world_top_right: [2.4, 12.192]
    world_bot_right: [2.4, 3.048]
    scan_angle_increment: 0.00872664625
    scan_angle_min: -1.5708
    scan_angle_max: 1.5708
    scan_range_min: 0.1
    scan_range_max: 50.0
    ray_step_size: 1
    
