gnss_to_local_node:
  ros__parameters:
    debug_mode: true
    map_ori_path: /home/autoware/gokart-autoware/src/universe/autoware.universe/gokart/configs/purdue_2024/map_ori.csv
    projection_center_latitude: 40.4377
    projection_center_longitude: -86.9444
    projection_lat_span: 0.001
    projection_lon_span: 0.0016
    set_origin: false
ekf_gnss_node:
  ros__parameters:
    frequency: 50
    origin_latitude: 40.4377
    origin_longitude: -86.9444
    origin_altitude: 172.91
purepursuit_node:
  ros__parameters:
    D: 0.45
    config_path: /home/autoware/gokart-autoware/src/universe/autoware.universe/gokart/configs/purdue_2024
    debug_mode: true
    interpScale: 20
    maxL: 4.0
    maxL_corner: 4.0
    maxP: 5.1
    maxP_corner: 5.1
    max_steer: 0.95
    minL: 2.0
    minL_corner: 2.0
    minP: 5.1
    minP_corner: 5.1
    vel_scale: 1.0
    wp_corner_filename: corner_wp_idx.npy
    wp_delim: ','
    wp_filename: wp.csv
    wp_overtake_filename: overtake_wp_idx.npy
    wp_skiprows: 1
    wp_x_idx: 0
    wp_y_idx: 1
    wp_v_idx: 2
visualize_node:
  ros__parameters:
    config_path: /home/autoware/gokart-autoware/src/universe/autoware.universe/gokart/configs/purdue_2024
    wp_centerline_filename: wp.csv
    wp_corner_filename: corner_wp_idx.npy
    wp_delim: ','
    wp_filename: wp.csv
    wp_overtake_filename: overtake_wp_idx.npy
    wp_skiprows: 1
    wp_track_width: 3.6
    wp_x_idx: 0
    wp_y_idx: 1
    wp_v_idx: 2
